apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-mtls-config
  namespace: hello
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 443 ssl;
        ssl_certificate /etc/nginx/tls/tls.crt;
        ssl_certificate_key /etc/nginx/tls/tls.key;
        ssl_client_certificate /etc/nginx/tls/ca.crt;
        ssl_verify_client on;

        location / {
          default_type text/html;
          return 200 'Hello World';
        }
      }
    }
